# Nombre de la app
spring.application.name=crud-estudiantes

# Base de datos H2 en memoria (no requiere instalar nada)
spring.datasource.url=jdbc:h2:mem:estudiantesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola web de H2 -> http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Puerto del servidor
server.port=8080
